<?php

$_SESSION['splash'] = true;
$error = '';

#file_put_contents("mylog.log", "\$_SESSION in Splash.php BEFORE changes = ".print_r($_SESSION,1)."\n\n\n", FILE_APPEND);
#error_log("\$_SESSION in Splash.php BEFORE changes = ".print_r($_SESSION,1));

if (!empty($_SESSION['user_data']['userid']) && (empty($_SESSION['authorized']) || $_SESSION['authorized'] !== true)){
    $error = '<br>The user ' . $_SESSION['user_data']['userid'] . " is not athorized to use this tool<br>\n";
    $_SESSION['splash'] = false;
}

#file_put_contents("mylog.log", "\$_SESSION in Splash.php AFTER changes = ".print_r($_SESSION,1)."\n\n\n", FILE_APPEND);
#file_put_contents("mylog.log", "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n\n\n\n\n\n\n", FILE_APPEND);

?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $config['app']['app_title']; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="style.v1.02.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.14.0/themes/base/jquery-ui.min.css"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.14.0/jquery-ui.min.js"></script>
    
</head>
<body>
    <div class="container">
        <div class="header row align-items-center" style="max-height: 102px;">
            <!-- <div class="col-sm-4">
            <img src="images/<?php echo $config['app']['app_logo']; ?>" class="logo" alt="<?php echo $config['app']['app_logo_alt']; ?>">
            </div>
            <div class="col-sm-4 text-center">
                <h1><?php echo $config['app']['app_title']; ?></h1>
            </div> -->
            <div class="col d-flex justify-content-center chirp_header" >
                <img class ="chirp_log" src="images/chirp-logo.png" alt="ChIRP Log" title="ChIRP">
            </div>
            <div class="col-sm-2 text-end">
                <?php
                if (!empty($_SESSION['user_data']['name'])) echo '<div id="username">Hello '.$_SESSION['user_data']['name'].'</div>'."\n";
                ?>
            </div>
        </div>
        <div id="bannerWrapperV">
            <div id="bannerTransV"></div>
            <div id="bannerTextV">
                <div class="bannerTextCenterV">
                    <p>P</p><p>I</p><p>L</p><p>O</p><p>T</p><p>&nbsp;</q><p>T</p><p>E</p><p>S</p><p>T</p><p>I</p><p>N</p><p>G</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 columns">
                <div>
                    <p class="chatIntro" >
                    ChIRP is a secure chatbot enabling NIH staff to use generative AI for their day-to-day work.
                    </p>
                </div>
                <div id="scrollContent">
                    <p>Chat for Intramural Research Program (ChIRP) stores all data locally in the NIH data center and uses a secure NIH STRIDES cloud account to host AI models. This enables staff to use ChIRP Chat for sensitive data workloads including:</p>
                    <ul>
                        <li>De-identified and anonymized clinical data</li>
                        <li>Pre-decisional and draft policy</li>
                        <li>Nonpublic data including scientific data and draft manuscripts</li>
                    </ul>
                    <p>
                        Please note that these use cases are specific to ChIRP, which is different than public AI tooling like ChatGPT, Meta.AI, and Google Gemini. When using any public AI tooling, please follow <a target="_blank" href="https://wiki.ocio.nih.gov/wiki/index.php/NIH_Artificial_Intelligence_(AI)_Cybersecurity_Guidance">OCIO Guidance</a>, which prohibits these sensitive workloads. Unlike the public tooling, data entered into ChIRP is not shared with Microsoft or OpenAI. This enables the sensitive workloads described above. Any questions, please contact <a href="mailto:CRISPI-LLM@od.nih.gov">CRISPI-LLM@od.nih.gov</a> via email.
                    </p>
                    <p>When using ChIRP, you must abide by these following guidelines:</p>
                    <ol type="1">
                        <li>
                            <b>Output Validation:</b> Review and validate outputs generated by ChIRP to ensure the application remains reliable, ethical, and valuable.
                        </li>
                        <li>
                            <b>Limitations and Biases:</b> Identify and report unfair, discriminatory, or inaccurate output patterns by the ChIRP.
                        </li>
                        <li>
                            <b>Ethical use:</b> Follow HHS and NIH policies including <a target="_blank" href="https://wiki.ocio.nih.gov/wiki/index.php/NIH_Artificial_Intelligence_(AI)_Cybersecurity_Guidance">OCIO Guidance</a>, 
                            <a target="_blank" href="https://intranet.hhs.gov/policy/hhs-policy-securing-artificial-intelligence-technology">HHS policy for Securing Artificial Intelligence (AI) Technology</a>, 
                            <a target="_blank" href="https://grants.nih.gov/grants/guide/notice-files/NOT-OD-23-149.html">NOT-OD-23-149 prohibiting Generative AI for NIH Peer Review</a>, and any other federal requirements.
                        </li>
                        <li> 
                            <b>No PII:</b> PII is not permitted for use but not limited to genomic data, passport information, social security numbers, driver's license numbers, Military status, bank account information including credit card numbers, photographic identifiers, medical record numbers, & date of birth.
                        </li>
                        <li> 
                            <b>Training Data:</b> ChIRP uses commercial models. It is not fine-tuned on NIH, OD, or biomedical topics. Do not expect ChIRP to have any internal knowledge of the NIH or OD.
                        </li>
                        <li> 
                            <b>Incident Response:</b> Report any malicious use or activity during the use of ChIRP immediately.
                        </li>
                    </ol>
<?php

//if (!empty($error)) echo '<span style="color:red">'.$error.'</span></p>'."\n";

//echo $config['app']['disclaimer_text'];

?>                


                </div>
                <div class="footer">
                    <p style="margin:10px 0 0 0; font-size:small;">
                        
                        <span><b>By clicking on Proceed you are agreeing to the above terms and conditions.</b></span>
                    </p>
                    <p id="proceedContainer">
                    <button class="proceedBtn" title="Click here to go to proceed" onclick="javascript: window.location.href = 'index.php';" id="proceedLink" ><u>I Agree</u>. Proceed</button></p>
                    <!-- Chat messages will be added here -->
                    <!-- <p><a title="Open the disclosure information in a new window" href="<?php echo $config['app']['disclosure_link']; ?>" target="_Blank" title="Vulnerability Disclosure">Vulnerability Disclosure</a></p> -->
                </div>
            </div>
            <div class="col-md-2 columns">
            </div>
        </div>
    </div>
    <div id="roleSelectionDlg" style="display:hidden">
        <div>
        Welcome to ChIRP (Chatbot for Intramural Research Program), a secure Large Language Models (LLMs) Environment Pilot.<br>
        Please indicate your main responsibility (functional role) at NIH:</br>
        <table style="width: 80%;text-align: center;"><tr>
        <td style="width: 33%;">
            <label for="administrative">Administrative</label>
            <input type="radio" id="administrative" name="userRole" value="Administrative">
        </td>
        <td >
            <label for="research">Research</label>
            <input type="radio" id="research" name="userRole" value="Research">
        </td>
        <td >
            <label for="other">Other</label>
            <input type="radio" id="other" name="userRole" value="Other">
        </td>
        </tr></table>
        </br>
        <p>
        By clicking the “Accept” button, you agree to allow us to collect your data entries (prompts) and responses from each LLM tool for aggregated usage analysis and statistical reporting purposes. If you do not wish to participate, click “Cancel” to be removed from this pilot.
        </p>
        </div>
    </div>
    <div id="newUserCapReachedExplnDlg" style="display:hidden">
        <div>
        Thank you for insteresting in ChIRP (Chatbot for Intramural Reasearch Program). Please note our user limit has been reached. 
        No more new users can access ChIRP at this point. </br>
        </div>
    </div>
    <div id="existUserCapReachedExplnDlg" style="display:hidden">
        <div>
        Thank you for your interest in ChIRP (Chatbot for Intramural Reasearch Program). Please note our user limit has been reached. 
        Inactive user can not access ChIRP at this point. Please go to <a href="registration.php">registration</a> page to register in the waiting list. </br>
        </div>
    </div>
    <div id="notRegisteredDlg" style="display:hidden">
        <!-- <div>
        Thank you for your interest in ChIRP (Chat for IRP). Registration is required for access. 
        Please go to the <a href="registration.php">registration</a> page to register. </br>
        </div> -->
        <div>
        Thank you for your interest in ChIRP (Chat for IRP). Registration is required for access. 
        Please go to the <a href="https://www.scgcorp.com/ChIRP2025/Registration">registration</a> page to register. </br>
        </div>
    </div>
</body>
</html>
<script>
    $(document).ready(function(){
        var userExist = <?php isUserExist($_SESSION['user_data']); ?>;
        $('#roleSelectionDlg').dialog({
            width: 960,
            autoOpen: false,
            title: 'Please Select a Role',
            open: function( event, ui ) {
                $(".ui-dialog-titlebar-close").hide();
                $("input[type='radio']").each(function(){
                    $(this).blur();
                });
            },
            buttons: [
                {
                    text: "Accept",
                    click: function() {
                        var selectedRole = $("input[name=userRole]:checked").val();
                        var firstName = "<?php if (!empty($_SESSION['user_data']['first_name'])) echo $_SESSION['user_data']['first_name']; else echo ""; ?>";
                        var lastName = "<?php if (!empty($_SESSION['user_data']['last_name'])) echo $_SESSION['user_data']['last_name']; else echo ""; ?>";
                        var preferredUsername = "<?php if (!empty($_SESSION['user_data']['preferred_username'])) echo $_SESSION['user_data']['preferred_username']; else echo ""; ?>";
                        var userid = "<?php if (!empty($_SESSION['user_data']['userid'])) echo $_SESSION['user_data']['userid']; else echo ""; ?>";
                        var ic = "<?php if (!empty($_SESSION['user_data']['department'])) echo $_SESSION['user_data']['department']; else echo ""; ?>";
                        var email = "<?php if (!empty($_SESSION['user_data']['email'])) echo $_SESSION['user_data']['email']; else echo ""; ?>";

                        if (typeof selectedRole == 'undefined') {
                            alert("Please select a role to proceed to the chat.");
                        } else {
                            //insert into users table
                            $.ajax({
                                url: "db.php",
                                type: 'POST',
                                data: {"callInsertUserData": "1", 
                                        "selectedRole": selectedRole,
                                        "first_name": firstName,
                                        "last_name": lastName,
                                        "preferred_username": preferredUsername,
                                        "userid": userid,
                                        "ic": ic,
                                        "email": email
                                    },
                                success: function(response) {                              
                                    if (response) {
                                        // console.log("insert user data ajax response: "+response);
                                        // $("#proceedLink")[0].click();
                                        userExist = true;
                                    }
                                }
                            }); 
                            
                            $( this ).dialog( "close" );
                        }
                    }
                },
                {
                    text: "Cancel",
                    click: function() {
                        $( this ).dialog( "close" );
                        window.location.href = "logout.php";
                    }
                },
            ]
        });
        $("#newUserCapReachedExplnDlg").dialog({
            width: 500,
            autoOpen: false,
            title: 'Thank you',
            open: function( event, ui ) {
                $(".ui-dialog-titlebar-close").hide();
            },
            buttons: [
                {
                    text: "Exit",
                    click: function() {
                        $( this ).dialog( "close" );
                        window.location.href = "logout.php";
                    }
                },
            ]
        });
        $("#existUserCapReachedExplnDlg").dialog({
            width: 500,
            autoOpen: false,
            title: 'Thank you',
            open: function( event, ui ) {
                $(".ui-dialog-titlebar-close").hide();
            },
            buttons: [
                {
                    text: "Register",
                    click: function() {
                        $( this ).dialog( "close" );
                        window.location.href = "registration.php";
                    }
                },
            ]
        });
        $("#notRegisteredDlg").dialog({
            width: 500,
            autoOpen: false,
            title: 'Thank you',
            open: function( event, ui ) {
                $(".ui-dialog-titlebar-close").hide();
            },
            buttons: [
                {
                    text: "Register",
                    click: function() {
                        $( this ).dialog( "close" );
                        //window.location.href = "registration.php";
                        window.location.href = "https://www.scgcorp.com/ChIRP2025/Registration";
                    }
                },
            ]
        });

        var reachUserCap = <?php checkIfReachUserCap(); ?>;
        var isUserRegistered = <?php is_user_registered($_SESSION['user_data']['userid'], $_SESSION['user_data']['email']); ?>;
        var isUserActive = <?php is_user_active($_SESSION['user_data']['userid'], $_SESSION['user_data']['email']); ?>;
        var checkExistingUserAccess = <?php checkExistingUserAccess($_SESSION['user_data']['userid'], $_SESSION['user_data']['email']); ?>;
        // console.log("userExist: "+userExist);

        if (!userExist) { //new user
            if (isUserRegistered && !reachUserCap) {
                $('#roleSelectionDlg').dialog("open");
                $("button.proceedBtn").prop("disabled", true);
            } else {
                var newUser = true;
                showNotAllowAccessDlg(newUser);
            }
            
            var scrollBarVisible = $('div#scrollContent').get(0).scrollHeight > $('div#scrollContent').innerHeight() ? true : false;
            //console.log("has scroll bar: " +scrollBarVisible);
            if (scrollBarVisible) {
                $('div#scrollContent').on('scroll', function() {
                    var elem = $(this);
                    if (userExist && elem.scrollTop() > 0 && 
                        ((elem[0].scrollHeight - elem.scrollTop()) <= (elem.outerHeight() + 1))) {
                        console.log("scroll to the bottom");
                        $("button.proceedBtn").prop("disabled", false);
                    }
                });
            } else {
                setTimeout(function() {
                    $("button.proceedBtn").prop("disabled", false);
                }, 10000);
            }
        } else { //existing user
            if (checkExistingUserAccess) { //allow access and update user info
                // console.log("Update user info");
                $.ajax({
                    url: "lib.required.php",
                    type: 'POST',
                    data: {"callUpdateUserInfo": "1"
                        },
                    success: function(response) {                              
                    }
                });                
            } else { //block the inactive user when user cap is reached
                var newUser = false;
                showNotAllowAccessDlg();
            }
        }

        function showNotAllowAccessDlg(newUser) {
            if (!isUserRegistered) {
                    $("#notRegisteredDlg").dialog("open");
                } else if (reachUserCap) {
                    if (newUser) {
                        $('#newUserCapReachedExplnDlg').dialog("open");
                    } else {
                        $('#existUserCapReachedExplnDlg').dialog("open");
                    }
                        
                }
                $("button.proceedBtn").prop("disabled", true);
                //console.log("User is not allowed to access and clear the session.")
                $.ajax({
                    url: "lib.required.php",
                    type: 'POST',
                    data: {"callClearSession": "1"},
                    success: function(response) {                              
                    }
                });
        }

    });
</script>
