name: Deploy Chirp

# Controls when the action will run.
on: workflow_dispatch

env:
  AZURE_WEBAPP_NAME: Chirp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '/var/www/chirp-dev.od.nih.gov'      # set this to the path to your web app project, defaults to the repository root
  PHP_VERSION: '8.3.6'                  # set this to the PHP version to use

permissions:
  contents: read

jobs:
  build and deploy:
  name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Deploy to openaivm'
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@10.178.73.4
          cd /var/www/chirp-dev.od.nih.gov
          git pull
